http:
  host: "0.0.0.0"
  port: "8081"
  
postal: 
  host: "ipapi.co"
  port: ""
  postalpath: "/{ipAddress}/json/"
  
weather: 
  host: "api.weatherapi.com"
  port: ""
  weatherPath: "/v1/forecast.json"
  days: "1"
  key: "45fcfe97d6d04ef5806205454221503"
  
fileList:
  host: "www.googleapis.com"
  fileListpath: "/drive/v3/files"
  
fileContent:
  host: "www.googleapis.com"
  fileContentpath: "/drive/v3/files/{fileId}" 

updateFileContent:
  host: "www.googleapis.com"
  fileContentpath: "/upload/drive/v2/files/{fileId}"

listOfStates:
  host: "app.zipcodebase.com"
  listOfStates: "/api/v1/country/province"  
  apiKey: "47210ca0-a6d9-11ec-964f-5b3972ecec1b"
  country: "US"
  
zipcode:
  host: "api.zip-codes.com"
  path: "/ZipCodesAPI.svc/1.0/GetAllZipCodes"  
  apiKey: "DEMOAPIKEY"
  country: "US"  