#%RAML 1.0 DataType

type: object
properties:
  kind:
    type: string
    required: true
    example: "drive#fileList"
  nextPageToken:
    type: string
    required: true
    example: "~!!~AI9FV7RnOE-l7ocYl8pTV9HRy2Ul89-DkqZ8lgIHMLlY91cx-Jks8ot5TGq4tS4MlF4vq4FLQtulFKIf6hMLq-uwAimfUQrY-lueJcB5iKpGw43GD-TdKDYI1oV0ApLsueU3JSowrvP-kFEyXsjzoREzBPTEZ9ahxBryXALfE4Y_SDlpAm6aYCDjcT6LXpiSjd_0WD1GyKgG7I4eVrNiHCdbjh_rKGPFcg-qs-SQeI0DQ0n2XB-QouJV_jP0SGECBXvNL1OSckeL2o1xJe3F9oISzxuuaG3_nMBfgNmOxjJvKFO7lsActWg="
  incompleteSearch:
    type: boolean
    required: true
    example: false
  files:
    type: array
    items:
      type: object
      properties:
        kind:
          type: string
          required: true
          example: drive#file
        id:
          type: string
          required: true
          example: 1lu4qtCzBDwd-Aw7I1kePfiPt2K7EhIwC
        name:
          type: string
          required: true
          example: Document from Lovely
        mimeType:
          type: string
          required: true
          example: application/vnd.ms-excel

            
    

    
    


